### PR TITLE
File archive support

### PR DESCRIPTION
**Pull request by debryant**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-embedded-data-logger-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add support for optionally moving closed tdms files to a user specified archive directory

### Why should this Pull Request be merged?

A directory of completed files can serve as a staging area for moving these to another location on the network

### What testing has been done?

Ran existing auto-tests. Added a new auto test for this feature. Manually tested the system explorer changes.

### Details of VI changes

**Shared**
Constants.vi
-Properties tab: Added entries for Log File Dir, Timestamp, Log Archive Dir, and Archive Files

**Configuration**
File Page:
-Added controls to the UI for Archive Files (boolean) and Archive Directory (Path)

Get Data Log File Settings.vi:
-Read Archive Files and Log Archive Dir properties
-Rearranged indicators on conpane to allow the Archive and Archive Log Directory to be side by side
-Replace hard coded constants with globals from Shared/Constants.vi

Build Data Log Archive Path.vi: (new)

**Engine**
File Logging Specification.ctl: 
-Add controls for Archive (boolean) and Archive Directory (path)

Get Data Log File Settings.vi
-Read Archive Files and Log Archive Dir properties
-Rearranged indicators on conpane to allow the Archive and Archive Log Directory to be side by side
-Replace hard coded constants with globals from Shared/Constants.vi

Initialize Logging Data.vi
-Wire Get Data Log File Settings.vi subVI's Archive and Archive Log Directory outputs into File Logging Specification cluster control

Asynchronous Logging Loop.vi:
-Initialize case: If Archive, create the Archive Directory hierarchy folders
-Close File: Move inner structure contents into subVI "Flush Close Archive File.vi"
-Shutdown case: Replace inner structure contents with subVI "Flush Close Archive File.vi"
   
Flush Close Archive File.vi: (new)
-Main code is from Asynchronous Logging Loop.vi Close/Shutdown cases
-Added support to move the file to the Archive Directory if Archive is True

Embedded Data Loggger Engine.lvlib:
-Add Flush Close Archive File.vi

**Tests**
Assert Log File Exists.vi: (new)
Assert Log File is Empty: (new)

EDL.vissdf
-Add 2nd logger definition for file archive testing

Embedded Data Logger System Tests.lvclass
-Add new VIs
-Various connector pane/state changes to other VIs

Log Command.vi
Log Trigger.vi
-Add param for Embedded Data Logger File Name so can use this VI for multiple data logger file tests

setUp.vi
-Delete pre-existing log directories before starting the testing

test Log Archive.vi (new)

test Log File.vi
-Update to param changes made to Log Command.vi and Log Trigger.vi

### CODE REVIEW

**Comment by debryant** [comment]
Good call on the location of where the log file definition is initially set. I updated the code to use that location. 

Regarding your comment on the **Archive Directory** always updating if **Archive Files** is disabled... This was agreed upon by Lynn and Darin in theory. We'll see if everyone continues to agree in practice.

**Comment by buckd** [comment]
> Regarding your comment on the **Archive Directory** always updating if **Archive Files** is disabled... This was agreed upon by Lynn and Darin in theory. We'll see if everyone continues to agree in practice.

If Darin has seen it and agreed, I'm good with it.

**Comment by debryant** [comment]
Added the library change.

**Comment by buckd** [comment]
image

This is the default log path the custom device gives me now for PharLap, Windows, VxWorks

**Comment by debryant** [comment]
image
Also, re-ran auto tests.

**Comment by debryant** [comment]
image

Also re-ran auto tests

**Comment by buckd** [comment]
@debryant Have you tested the log archive on a remote target or just using the Windows automated test?

**Comment by debryant** [comment]
Yes, I tested the log archive feature on a Linux 64bit target.
Also, just found a bug in deleting the index file. Ironically this case was tested incorrectly in a unit test :( so I fixed that too.

**Pull request merged**
