### PR TITLE
Fix #23: Enforce minimum file span size and time

### LINKED ISSUE #23: File and time segmenting values can be set to zero, breaking the custom device
**Describe the bug**
The UI allows values which will break the custom device to be entered. You should never segment at zero seconds or zero MB.

**To Reproduce**
Configure the custom device to log to a file, segmenting based on file size with the size set to zero. Map ~20 channels to the log file and deploy. When logging is enabled, observe that the FIFO utilization immediately shoots up towards the 100%.

**Expected behavior**
These values should have a reasonable, non-zero minimum. For size, that is probably 1MB. For time duration, that may be a higher number, since segmenting every second likely doesn't make much sense (although we could allow it).

**Screenshots**
image

**Desktop (please complete the following information):**
Tested with on a PXI NI Linux RT target.

**Additional context**

### PR DESCRIPTION
**Pull request by Karl-G1**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-embedded-data-logger-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This change enforces a minimum file span size of 1MB and time of 30 seconds by coercing the new value set in the control. This was implemented in the block diagram code instead of the control's properties to allow a different span value depending on span mode, as well as to be more readable.

### Why should this Pull Request be merged?

Address Issue #23 where the user was allowed to enter a file span size of 0MB and time of 0 seconds. This behavior causes the logging engine to break.

### What testing has been done?

Built the custom device and tested in VeriStand 2018.

### Note

If users set a value lower than the minimum in the system definition file or in a build before this change goes in, the value will be coerced silently when the Log File page is opened next.

### CODE REVIEW

**Comment by rtzoeller** [comment]
Random musings more than actual feedback:

**Comment by Karl-G1** [comment]
I corrected the control's spelling.
If you have a better recommendation for selecting the Segment File By value, I'm fine with implementing it, but I'm also fine with leaving it be :)

**Comment by rtzoeller** [comment]
I believe it is currently a ring, which is why we don't get type safety when hooking it up to a case structure. Ideally it would have been an enum.

I don't consider the onus on you to fix this; it should have been thought about during the original submission. Then we would not have to rely on "not-equal-to-zero" checks elsewhere in the code.
image

**Comment by Karl-G1** [comment]
> image
> To @rtzoeller 's comment, this is the equivalent of C++ `numeric_limits<uint32_t>::max()` and I would recommend using that.

Committed the replacement with some mild snark.

**Pull request merged**
